In [22]:
import numpy as np
import pandas as pd
from datetime import datetime

In [23]:
df=pd.read_csv(r'cars.csv')

In [24]:
df.head()

,Make,Model,Year,Fuel_Type,Transmission,Engine_Size,Mileage,Horsepower,Torque,Owners,Accident_History,Service_History,Color,Body_Type,Drivetrain,Fuel_Efficiency,Location,Selling_Price
0,Mercedes-Benz,GLE,2024,Petrol,Automatic,2.3,100,186.0,196.0,1,0.0,NaN,Silver,SUV,AWD,30.0,IL,64140
1,Hyundai,Tucson,2008,Petrol,Automatic,2.3,387035,189.0,190.0,4,0.0,NaN,Blue,SUV,FWD,35.0,FL,500
2,Volkswagen,Golf,2021,Hybrid,NaN,1.9,46054,158.0,153.0,1,0.0,Partial Service,Gray,Hatchback,AWD,43.0,NY,16429
3,Chevrolet,Tahoe,2005,Petrol,NaN,2.2,141302,169.0,165.0,5,1.0,No Service,Blue,SUV,AWD,NaN,FL,2199
4,Toyota,Camry,2022,Petrol,Automatic,1.9,32813,149.0,141.0,1,0.0,Full Service,Brown,Sedan,FWD,38.0,CA,21792

In [ ]:
now = datetime.now()

current_year = now.year
current_month = now.month
current_day = now.day

In [26]:
df["car_age_months"] = (current_year - df["Year"]) * 12 + (current_month - 1)

In [27]:
print(df[["Make", "Model", "Year", "car_age_months"]].head(10))

            Make    Model  Year  car_age_months
0  Mercedes-Benz      GLE  2024              33
1        Hyundai   Tucson  2008             225
2     Volkswagen     Golf  2021              69
3      Chevrolet    Tahoe  2005             261
4         Toyota    Camry  2022              57
5      Chevrolet  Equinox  2008             225
6         Nissan   Sentra  2022              57
7  Mercedes-Benz  C-Class  2022              57
8            BMW       X3  2023              45
9          Honda    Pilot  2020              81

In [28]:
df.to_csv("cars.csv", index=False)

In [30]:
pd.read_csv("cars.csv").head(3)

,Make,Model,Year,Fuel_Type,Transmission,Engine_Size,Mileage,Horsepower,Torque,Owners,Accident_History,Service_History,Color,Body_Type,Drivetrain,Fuel_Efficiency,Location,Selling_Price,car_age_months
0,Mercedes-Benz,GLE,2024,Petrol,Automatic,2.3,100,186.0,196.0,1,0.0,NaN,Silver,SUV,AWD,30.0,IL,64140,33
1,Hyundai,Tucson,2008,Petrol,Automatic,2.3,387035,189.0,190.0,4,0.0,NaN,Blue,SUV,FWD,35.0,FL,500,225
2,Volkswagen,Golf,2021,Hybrid,NaN,1.9,46054,158.0,153.0,1,0.0,Partial Service,Gray,Hatchback,AWD,43.0,NY,16429,69